### PR TITLE
Pubsub in ci

### PR DESCRIPTION
**Pull request by bretambrose**
* Run pub sub node sample with both direct mqtt and websocket configurations in CI

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TingDaoK** [comment]
Why not use github actions to run the samples as well?

**Comment by bretambrose** [comment]
> 
> 
> Why not use github actions to run the samples as well? Feel like if we can add tests steps to `builder.json`. We can store the credentials in github secrets as what we did for other repos? In this way we can test it across platform?

We can't use internal VPC infrastructure then: no proxies, no event stream servers, no gg cores

**Review by justinboswell — APPROVED** [review]

**Comment by TingDaoK** [comment]
> > Why not use github actions to run the samples as well? Feel like if we can add tests steps to `builder.json`. We can store the credentials in github secrets as what we did for other repos? In this way we can test it across platform?
> 
> We can't use internal VPC infrastructure then: no proxies, no event stream servers, no gg cores

Do we need proxies and gg cores for pubsub sample?

**Comment by bretambrose** [comment]
> 
> 
> > > Why not use github actions to run the samples as well? Feel like if we can add tests steps to `builder.json`. We can store the credentials in github secrets as what we did for other repos? In this way we can test it across platform?
> > 
> > 
> > We can't use internal VPC infrastructure then: no proxies, no event stream servers, no gg cores
> 
> Do we need proxies and gg cores for pubsub sample?

Atm? no.  Eventually?  yes.

**Review by TingDaoK — APPROVED** [review]
yeah, just feel like if we can have at least one sample (pubsub that only needs the credentials to run) runs across platform, we can be more confident. For the other samples, we need the internal environment for sure. Anyway, this is good! We finally have our samples tested!🙆‍♂️

**Comment by bretambrose** [comment]
> yeah, just feel like if we can have at least one sample (pubsub that only needs the credentials to run) runs across platform, we can be more confident. For the other samples, we need the internal environment for sure. Anyway, this is good! We finally have our samples tested!ok_man

I think what you're thinking of here is a separate {OS x Architecture} test set that would verify/validate that all of the expected, embedded native libraries are present and invoked properly.  We could definitely do that with containers/builder but probably limit it to just successfully creating a single native resource (elg, for example).  Ideally, we should do it as a RC test step in CD pipelines as well.  I'm going to add both of these ideas to the IoT Quality doc.

**Pull request merged**
